### ISSUE TITLE
Have explicite brigde name in Vagrant file

### ISSUE THREAD

**Issue by stappersg** [tinkerbell/sandbox#140]
## Expected Behaviour

A Tinkerbell sandbox Vagrant file that tells which brigde it needs.

It will making overriding the default bridge name possible.

Making it possible to deal with an error like:
 
```text
/usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam. (Libvirt::Error)
```

## Current Behaviour
Upon  `vagrant up` I get
```text
   ...
==> provisioner:  -- Video VRAM:        256
==> provisioner:  -- Video 3D accel:    false
==> provisioner:  -- Sound Type:	
==> provisioner:  -- Keymap:            en-us
==> provisioner:  -- TPM Backend:       passthrough
==> provisioner:  -- TPM Path:          
==> provisioner:  -- INPUT:             type=mouse, bus=ps2
==> provisioner: Removing domain...
==> provisioner: Deleting the machine folder
/usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam. (Libvirt::Error)
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `block in libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:64:in `block (2 levels) in call'
  ....
  ....
```

## Possible Solution

An alternative solution could be _comment in Vagrant file_ that tells how to enable _verbose mode_.

## Steps to Reproduce (for bugs)

As documented at https://github.com/tinkerbell/sandbox/blob/main/docs/quickstarts/VAGRANTLVIRT.md

## Context

I would like to try out  _Tinkerbell_.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

Linux, Debian,  AMD64

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

Vagrant & Libvirt

* Link to your project or a code example to reproduce issue:

Computer being used has some **non default**  _netwerk interfaces_
```text
$ ip --brief link show
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
enxe4b97a90028f  UP             e4:b9:7a:90:02:8f <BROADCAST,MULTICAST,UP,LOWER_UP> 
wlp59s0          DOWN           d2:82:89:f2:51:8e <NO-CARRIER,BROADCAST,MULTICAST,UP> 
ovs-system       UNKNOWN        6e:bc:cb:93:09:25 <BROADCAST,MULTICAST,UP,LOWER_UP> 
ovsbr0           UNKNOWN        f6:eb:8e:8b:03:4c <BROADCAST,MULTICAST,UP,LOWER_UP> 
virbr0           DOWN           52:54:00:e7:b9:e6 <NO-CARRIER,BROADCAST,MULTICAST,UP> 
docker0          DOWN           02:42:f2:b3:14:3c <NO-CARRIER,BROADCAST,MULTICAST,UP> 
br-ef0377b931aa  DOWN           02:42:31:e3:1b:1f <NO-CARRIER,BROADCAST,MULTICAST,UP> 
```

**Comment by stappersg** [comment]
Partial output of `vagrant up --debug`:
```text
   ....
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyDomain:0x00005556e9dd38b8>
 INFO interface: info: Removing domain...
 INFO interface: info: ==> provisioner: Removing domain...
==> provisioner: Removing domain...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyNetworks:0x00005556e9c8bf50>
 INFO destroy_networks: Checking if any networks were created
 INFO machine: New machine ID: nil
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CleanMachineFolder:0x00005556e9eba4e8>
 INFO interface: info: Deleting the machine folder
 INFO interface: info: ==> provisioner: Deleting the machine folder
==> provisioner: Deleting the machine folder
DEBUG create_domain: Recursively removing: /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt
 INFO warden: Calling IN action: #<Proc:0x00007f01a46b9700 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<Proc:0x00007f01a4a4df10 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a47bdf70>
DEBUG storeboxmetadata: Writing box metadata file to /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a47bdf70>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a4a4dce0>
DEBUG storeboxmetadata: Writing box metadata file to /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a4a4dce0>
 INFO warden: Calling OUT action: #<Proc:0x00007f01a4a4df10 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a46b94a8>
DEBUG storeboxmetadata: Writing box metadata file to /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a46b94a8>
 INFO warden: Calling OUT action: #<Proc:0x00007f01a46b9700 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::CleanMachineFolder:0x00005556e9eba4e8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyNetworks:0x00005556e9c8bf50>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::DestroyDomain:0x00005556e9dd38b8>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::PruneNFSExports:0x00005556e994b228>
 INFO warden: Calling OUT action: #<VagrantPlugins::ProviderLibvirt::Action::ClearForwardedPorts:0x00005556e981f548>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ProvisionerCleanup:0x00005556e91fe330>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a48853b8>
DEBUG storeboxmetadata: Writing box metadata file to /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a48853b8>
 INFO warden: Calling OUT action: #<Proc:0x00007f01a4885408 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::Call:0x00007f01a4a4e078>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a4b6ce00>
DEBUG storeboxmetadata: Writing box metadata file to /home/gs0604/src/tinkerbell/sandbox/deploy/vagrant/.vagrant/machines/provisioner/libvirt/box_meta
 INFO warden: Calling OUT action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x00007f01a4b6ce00>
 INFO warden: Calling OUT action: #<Proc:0x00007f01a4b6ce28 /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:126 (lambda)>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::Call:0x00007f01a47be010>
 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x00007f01a47be088>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x00005556ea17c7a8>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-3894af1b6d0b328c1d47c793c8ec659c
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007f01a482d190>
/usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam. (Libvirt::Error)
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `block in libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:64:in `block (2 levels) in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:52:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:52:in `block in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:49:in `synchronize'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:49:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_domain.rb:465:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_domain_volume.rb:94:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/handle_box_image.rb:123:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
```

**Comment by stappersg** [comment]
_text version_
```text
$ virsh net-list --all
 Name   State   Autostart   Persistent
----------------------------------------

$ virsh --connect qemu:///system net-list --all
 Name              State      Autostart   Persistent
------------------------------------------------------
 default           active     yes         yes
 mcvlan-dck-home   inactive   no          yes
 vmrtr-net         active     yes         yes

$ 
```

I'm not sure in which direction to continue with this issue. Choosing between _vagrant issue_ or _tinkerbell issue_.

**Comment by stappersg** [comment]
It seems to be a _vagrant issue_.
I think there is no need to keep this open.
```text
stappers@myhost:~
$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Box 'debian/buster64' could not be found. Attempting to find and install...
    default: Box Provider: libvirt
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/buster64'
    default: URL: https://vagrantcloud.com/debian/buster64
==> default: Adding box 'debian/buster64' (v10.20220328.1) for provider: libvirt
    default: Downloading: https://vagrantcloud.com/debian/boxes/buster64/versions/10.20220328.1/providers/libvirt.box
==> default: Successfully added box 'debian/buster64' (v10.20220328.1) for 'libvirt'!
==> default: Uploading base box image as volume into Libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              stappers_default
==> default:  -- Description:       Source: /home/stappers/Vagrantfile
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Feature:           acpi
==> default:  -- Feature:           apic
==> default:  -- Feature:           pae
==> default:  -- Clock offset:      utc
==> default:  -- Memory:            1024M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Nvram:             
==> default:  -- Base box:          debian/buster64
==> default:  -- Storage pool:      default
==> default:  -- Image(vda):        /var/lib/libvirt/images/stappers_default.img, virtio, 20G
==> default:  -- Disk driver opts:  cache='default'
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     -1
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        16384
==> default:  -- Video 3D accel:    false
==> default:  -- Sound Type:	
==> default:  -- Keymap:            en-us
==> default:  -- TPM Backend:       passthrough
==> default:  -- TPM Path:          
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default: Removing domain...
==> default: Deleting the machine folder
/usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `bridge_name': Call to virNetworkGetBridgeName failed: internal error: netwerk 'vmrtr-net' heeft geen brug naam. (Libvirt::Error)
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:190:in `block in libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/util/network_util.rb:159:in `libvirt_networks'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:64:in `block (2 levels) in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:52:in `each'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:52:in `block in call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:49:in `synchronize'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_networks.rb:49:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_domain.rb:465:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/create_domain_volume.rb:94:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/handle_box_image.rb:123:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/handle_storage_pool.rb:63:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.8.0/lib/vagrant-libvirt/action/cleanup_on_failure.rb:21:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:31:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
stappers@myhost:~
$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.box = "debian/buster64"
  
    config.vm.network "private_network", ip: "192.168.33.10"
  
    config.vm.provider "libvirt" do |l|
      l.memory = "1024"
    end
end
stappers@myhost:~
$ 
```
